name: 'Code coverage comments'
description: 'Comment code coverage from lcov.info file in commits or PRs'
inputs:
  github-token:
    description: Github token
    required: true
    default: ${{ github.token }}
  coverage-file-path:
    description: 'Path to `lcov.info` or `clover.xml` file. It has to include the filename so we can determine how to parse the coverage result.'
    required: true
    default: './coverage/clover.xml'
  delete-old-comments:
    description: 'Set to `true` to delete old coverage comments.'
    required: false
    default: true
runs:
  using: 'node16'
  main: 'dist/index.js'
